// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package io.demo;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
